pipeline {
    agent any

    stages {
        stage('WithEnv Script') {
            steps {
                withEnv(['VALUE=foo!']) {
                    sh 'cd script;./build.sh'
                }
            }
        }
    }
}